Add support for OGC:API features & extend OGC:API tiles functionality
PDOK/ngr-services-spider pull request #27
Opened 2023-08-22 10:26 UTC by kad-rothul

# Omschrijving

Een omschrijving van wat je hebt toegevoegd/veranderd:

https://dev.kadaster.nl/jira/browse/PDOK-15473

Functionaliteit toegevoegd om OGC:API features op te halen en op de juiste manier te verwerken en functionaliteit van vectortiles uitgebreid. Extra script toegevoegd om een lokale image van de ngr-spider te testen met deze ogc-api protocols.

NB: Omdat er in NGR nog geen ogcapi features records zijn, is dit deel nog niet geheel functioneel, omdat het niet getest kan worden. Er staan #TODO in de code, er is een issue voor aangemaakt in deze repo (zie: ) en een vervolgticket in Jira (zie: https://dev.kadaster.nl/jira/browse/PDOK-15645)

## Type verandering

(Verwijder de opties die niet relevant zijn.)

- Minor change (typo, formatting, version bump)
- Nieuwe feature
- Verbetering oude feature

# Checklist:

- [X] Ik heb de code in deze PR zelf nogmaals nagekeken
- [X] Ik heb mijn code beter achtergelaten dan dat ik het aantrof
- [ ] De code is leesbaar en de moeilijke onderdelen zijn voorzien van commentaar
- [ ] Ik heb de tests toegevoegd/uitgebreid indien nodig
- [ ] Ik heb de tests gedraaid die de werking van mijn wijziging bewijst
- [X] Er zit geen gevoelig informatie in deze PR (wachtwoorden etc)

2023-08-22 15:49 UTC, RoelvandenBerg requested changes
A few things. generally looks good. Did not test it, can you show me example output? (I'm a bit lazy :grimacing: )

2023-08-22 15:49 UTC, RoelvandenBerg commented on README.md
>  python3 -m build
these two lines should be replaced by 

```suggestion
python3 -m pip install -e .
```

2023-08-22 15:49 UTC, RoelvandenBerg commented on examples/generate-pdok-services-plugin-config-ogcapi.sh
> +#!/usr/bin/env bash
I would expect to find this in the qgis plugin (as this is a testcase for the plugin?)

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +import urllib.request
project also uses requests library. I would prefer to use `requests` library for this (easier / simpler). (but stick to the `urllib` `parse` methods as those are not part of requests.

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +            self.json = json.load(url)
requests has a json method: 

```
resp = requests.get(href)
self.json = resp.json()

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +        with urllib.request.urlopen(href) as url:
same here about requests

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +#TODO implement class to retrieve correct info
TODO?

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +    except Exception:
(too) broad except? Is there a way to make this more specfic?

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/constants.py
> +LOOKUP = {
Name too generic name imho. `PROTOCOL_LOOKUP` perhaps?

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +    except Exception:
Where do you expect the error to come from?

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +        title = oaf.title
see: https://github.com/PDOK/ngr-services-spider/blame/6b96d4dc639998cbdaf0d39b1e7e5975e0023360/ngr_spider/ogc_api_tiles.py#L151 I think you can do something of the like here:

```
>>> x = None
>>> y = ""
>>> z = x or y or "hello"
>>> z
'hello'
```
so I would be fine with:

```
title = oaf.title or oaf.service_desc.get_info().title or ""
```

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +        title = oaf.title
And I would expect this to be resolved in oaf itself tbh. Or is there a reason for `oaf.title` to differ from `oaf.service_desc.get_info().title?`

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +        service_layer_metadata_id: str = "ervice_layer_metadata_id"
```suggestion
        service_layer_metadata_id: str = "service_layer_metadata_id"
```

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +    def __load_landing_page(self, service_url: str):
I prefer just a single underscore. https://docs.python-guide.org/writing/style/#we-are-all-responsible-users

2023-08-22 15:49 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +        with urllib.request.urlopen(service_url) as response:
urlopen -> requests

2023-08-23 07:11 UTC, kad-rothul commented on README.md
>  python3 -m build
Als ik het goed begrijp zou: 
`
python3 -m build
python3 -m pip install dist/ngr_spider-0.6.1-py3-none-any.whl 
`

in zijn geheel vervangen kunnen worden door:
`
python3 -m pip install -e .
`
?

PS: Ik lees nu dat `python3 -m pip install -e .` voor development praktischer is dan `pip install .` wat ik heb gebruikt

2023-08-23 07:16 UTC, kad-rothul commented on examples/generate-pdok-services-plugin-config-ogcapi.sh
> +#!/usr/bin/env bash
Hier heb je wel een punt. Het is inderdaad een testcase/script voor de plugin, aan de andere kant gebruikt het wel de ngr-spider. Ik denk dat die inderdaad verwijderd kan worden uit deze PR.

2023-08-23 07:23 UTC, RoelvandenBerg commented on README.md
>  python3 -m build
ja inderdaad

2023-08-23 07:44 UTC, kad-rothul commented on ngr_spider/util.py
> +        title = oaf.title
Deze functionaliteit heb ik eigenlijk overgenomen van de tiles functie in de util.py. Ik had ook het idee dat het wat omslachtig was, maar omdat ik nog geen mogelijkheid had om het te testen had ik het zo gelaten. Ook bijvoorbeeld "Or is there a reason for oaf.title to differ from oaf.service_desc.get_info().title?" zou ik niet perse kunnen beantwoorden omdat ik dit niet kan testen met een oaf record.

2023-08-23 08:50 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +        title = oaf.title
Kan je dat teruglezen in de code?

2023-08-23 08:57 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +        title = oaf.title
Alsin: waar komt die oaf.service_desc.get_info().title vandaan?

2023-08-23 08:57 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +        title = oaf.title
als dat een andere plek uit de metadata is dan is dit inderdaad correct

2023-08-23 11:10 UTC, kad-rothul commented on ngr_spider/util.py
> +        title = oaf.title
Uit de serviceDesc komt:

"description": "BGT OGC API specificatie",
      "title": "BGT OGC API",
      "version": "1.0.0"
      
terwijl als je naar oaf.title/description kijkt, krijg je:
"title": "BGT",
  "description": "De BGT, Basisregistratie Grootschalige Topografie, wordt de gedetailleerde grootschalige basiskaart (digitale kaart) van heel Nederland, waarin op een eenduidige manier de ligging van alle fysieke objecten zoals gebouwen, wegen, water, spoorlijnen en (landbouw)terreinen is geregistreerd."
  
  Wat dus inderdaad anders is: De ene kijkt op:
  https://api.pdok.nl/lv/bgt/ogc/v0_1, de andere op:
  https://api.pdok.nl/lv/bgt/ogc/v0_1/api?f=json
  
  Dus dan kan ik het beter op deze manier laten staan lijkt mij

2023-08-23 11:22 UTC, kad-rothul commented on ngr_spider/util.py
> +        title = oaf.title
In het features endpoint op https://api.pdok.nl/lv/bgt/oaf/v1_0 staat bijv. geen title en description: Deze staan wel in /api, dus in dat geval is het beter om allebei te checken. Ik stel voor om voor nu dit zo te laten, en wanneer features ogcapi door pdok verder ontwikkelt wordt, dit correct wordt gemaakt, dat is veel makkelijker dan nu 'voorspellen' waar de info vandaag gaat komen.

2023-08-30 12:37 UTC, RoelvandenBerg commented on ngr_spider/util.py
> +        title = oaf.title
Eens

2023-08-30 12:41 UTC, RoelvandenBerg requested changes
nog een klein dingetje

2023-08-30 12:41 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +        return self.json["tags"]
Dit levert een KeyError op als tags niet bestaan. Ik denk dat het ok is om deze change te houden zoals het was. `self.json.get('tags', []) or []`

2023-08-30 12:41 UTC, RoelvandenBerg commented on ngr_spider/ogc_api_features.py
> +        return self.json["tags"]
maar dan dus met `or`

2023-09-01 11:14 UTC, RoelvandenBerg approved these changes

2023-09-04 08:45 UTC, merged